### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ThePronixowy** [CedarBlocks/Simple-Discord-Bot-Website#4]
Hi, i have a little problem. I have a website in ct8.pl, and i drop website in the folder for domains. And i have a bug. Website: http://ebots.ct8.pl/ . Do you help me? Please

**Comment by CedarBlocks** [comment]
What seems to be the problem? Can you expound?

**Comment by ThePronixowy** [comment]
I don't know how to get a normal website, a buttons and more. No Index Of . :/

**Comment by CedarBlocks** [comment]
> I don't know how to get a normal website, a buttons and more. No Index Of . :/

I can't really help you with hosting it.
I would recommend looking into these if you want a free host:
￼￼ https://glitch.com or https://replit.com

I personally use of glitch in like it a lot!
Hope that helps.￼

**Comment by CedarBlocks** [comment]
Also I can probably make A tutorial on how to host it once I get out of school on spring break.￼￼￼
